# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        MODE: mitogen
      #Python35:
        #python.version: '3.5'
        #MODE: mitogen
      #Python36:
        #python.version: '3.6'
        #MODE: mitogen
      #Python37:
        #python.version: '3.7'
        #MODE: mitogen

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: virtualenv
